set(KAONIC_RFA_GPIO_RST_CHIP "/dev/gpiochip0" CACHE STRING "RF A reset GPIO chip")
set(KAONIC_RFA_GPIO_RST_LINE 21 CACHE STRING "RF A reset GPIO line")
set(KAONIC_RFA_GPIO_IRQ_CHIP "/dev/gpiochip0" CACHE STRING "RF A IRQ GPIO chip")
set(KAONIC_RFA_GPIO_IRQ_LINE 22 CACHE STRING "RF A IRQ GPIO line")

set(KAONIC_RFB_GPIO_RST_CHIP "/dev/gpiochip0" CACHE STRING "RF B reset GPIO chip")
set(KAONIC_RFB_GPIO_RST_LINE 21 CACHE STRING "RF B reset GPIO line")
set(KAONIC_RFB_GPIO_IRQ_CHIP "/dev/gpiochip0" CACHE STRING "RF B IRQ GPIO chip")
set(KAONIC_RFB_GPIO_IRQ_LINE 22 CACHE STRING "RF B IRQ GPIO line")

set(KAONIC_RFA_SPI_PATH "/dev/spidev0.0" CACHE STRING "RF A SPI path")
set(KAONIC_RFA_SPI_SPEED 25000000 CACHE STRING "RF A SPI speed")
set(KAONIC_RFA_SPI_MODE 0 CACHE STRING "RF A SPI mode")
set(KAONIC_RFA_SPI_BPW 8 CACHE STRING "RF A SPI bits per word")

set(KAONIC_RFB_SPI_PATH "/dev/spidev0.0" CACHE STRING "RF B SPI path")
set(KAONIC_RFB_SPI_SPEED 25000000 CACHE STRING "RF B SPI speed")
set(KAONIC_RFB_SPI_MODE 0 CACHE STRING "RF B SPI mode")
set(KAONIC_RFB_SPI_BPW 8 CACHE STRING "RF B SPI per word")

set(KAONIC_SERVER_ADDR "0.0.0.0" CACHE STRING "GRPC server address")
set(KAONIC_SERVER_PORT "50051" CACHE STRING "GRPC server port")

set(KAONIC_SERIAL_TTY_PATH "/dev/tty0" CACHE STRING "Serial TTY path")
set(KAONIC_SERIAL_BAUD_RATE 115200 CACHE STRING "Serial baud rate")

configure_file(${CMAKE_SOURCE_DIR}/kaonic/config.in ${CMAKE_BINARY_DIR}/config.hpp @ONLY)
include_directories(${CMAKE_BINARY_DIR})
