set(DEFAULT_GPIO_CHIP "gpiochip0" CACHE STRING "Default gpio chip")
set(DEFAULT_RST_CHIP_LINE 21 CACHE STRING "Default reset chip line")
set(DEFAULT_IRQ_CHIP_LINE 22 CACHE STRING "Default IRQ chip line")

set(DEFAULT_SPI_DEVICE_PATH "/dev/spi" CACHE STRING "Default SPI path")
set(DEFAULT_SPI_SPEED 500000 CACHE STRING "Default SPI speed")
set(DEFAULT_SPI_MODE 1 CACHE STRING "Default SPI mode")
set(DEFAULT_SPI_BPW 8 CACHE STRING "Default SPI bits per word")

set(DEFAULT_SERVER_ADDR "0.0.0.0" CACHE STRING "Default GRPC server address")
set(DEFAULT_SERVER_PORT "50051" CACHE STRING "Default GRPC server port")

set(DEFAULT_SERIAL_TTY_PATH "/dev/tty0" CACHE STRING "Default Serial TTY path")
set(DEFAULT_SERIAL_BOUND_RATE 115200 CACHE STRING "Default Serial bound rate")

set(GPIO1_CHIP ${DEFAULT_GPIO_CHIP} CACHE STRING "GPIO1 chip")
set(GPIO1_RST_LINE ${DEFAULT_RST_CHIP_LINE} CACHE STRING "GPIO1 Reset chip line")
set(GPIO1_IRQ_LINE ${DEFAULT_IRQ_CHIP_LINE} CACHE STRING "GPIO1 IRQ chip line")

set(GPIO2_CHIP ${DEFAULT_GPIO_CHIP} CACHE STRING "GPIO2 chip")
set(GPIO2_RST_LINE ${DEFAULT_RST_CHIP_LINE} CACHE STRING "GPIO2 Reset chip line")
set(GPIO2_IRQ_LINE ${DEFAULT_IRQ_CHIP_LINE} CACHE STRING "GPIO2 IRQ chip line")

set(SPI1_DEVICE_PATH ${DEFAULT_SPI_DEVICE_PATH} CACHE STRING "SPI1 path")
set(SPI1_SPEED ${DEFAULT_SPI_SPEED} CACHE STRING "SPI1 speed")
set(SPI1_MODE ${DEFAULT_SPI_MODE} CACHE STRING "SPI1 mode")
set(SPI1_BPW ${DEFAULT_SPI_BPW} CACHE STRING "SPI1 bits per word")

set(SPI2_DEVICE_PATH ${DEFAULT_SPI_DEVICE_PATH} CACHE STRING "SPI2 path")
set(SPI2_SPEED ${DEFAULT_SPI_SPEED} CACHE STRING "SPI2 speed")
set(SPI2_MODE ${DEFAULT_SPI_MODE} CACHE STRING "SPI2 mode")
set(SPI2_BPW ${DEFAULT_SPI_BPW} CACHE STRING "SPI2 bits per word")

set(SERVER_ADDR ${DEFAULT_SERVER_ADDR} CACHE STRING "GRPC server address")
set(SERVER_PORT ${DEFAULT_SERVER_PORT} CACHE STRING "GRPC server port")

set(SERIAL_TTY_PATH ${DEFAULT_SERIAL_TTY_PATH} CACHE STRING "Serial TTY path")
set(SERIAL_BOUND_RATE ${DEFAULT_SERIAL_BOUND_RATE} CACHE STRING "Serial bound rate")

configure_file(${CMAKE_SOURCE_DIR}/kaonic/config.in ${CMAKE_BINARY_DIR}/config.hpp @ONLY)
include_directories(${CMAKE_BINARY_DIR})
